In [3]:
# Importing modules
import pandas as pd
import numpy as np

In [ ]:
# Reading the dataset 1
df = pd.read_csv('Data/amazon_scraped_backup.csv')
df

,Device,Price,Rating
0,"Lava Bold N2 (Siachen White, 4 GB RAM, 64 GB S...","₹9,299.00",3.7 out of 5 stars
1,"Lava Bold N4 Lite (Empire Gold, 3GB RAM, 32GB ...","₹9,299.00",3.3 out of 5 stars
2,"Samsung Galaxy M07 Mobile (Black, 4GB RAM, 64G...","₹15,999.00",4.1 out of 5 stars
3,"REDMI A7 Pro 5G (Black, 4GB RAM,128GB Storage)...","₹12,498.00",3.5 out of 5 stars
4,"Lava Agni 4 5G (8GB RAM, 256GB Storage, Phanto...","₹14,499.00",4.3 out of 5 stars
...,...,...,...
239,realme 16x 5G Smartphone 4+128GB White,"₹27,980.00",4.4 out of 5 stars
240,"BlackBerry KEYone 32GB BBB100-1 - 4.5"" Inch Fa...","₹78,500.00",3.1 out of 5 stars
241,"Redmi Note 17 5G (Dark Night, 6GB RAM, 128GB R...","₹23,999.00",3.2 out of 5 stars
242,"Philips S7221 5G Smartphone (Blue) | 6.67"" HD+...","₹29,999.00",3.0 out of 5 stars
243,PEACE Aura 26 4G Smartphone with 6.67-inch Dis...,"₹10,999.00",NaN

In [ ]:
# Reading the dataset 2
df2 = pd.read_csv('Data/amazon_scraped_backup_2.csv')
df2

,Device,Price,Rating
0,"Redmi Note 17 5G (Dark Night, 6GB RAM, 128GB R...","₹23,999.00",3.2 out of 5 stars
1,"REDMI Note 15 Pro 5G (Silver Ash, 8GB+128GB) |...","₹39,999.00",3.9 out of 5 stars
2,"Lava Agni 4 5G (8GB RAM, 256GB Storage, Phanto...","₹14,499.00",4.3 out of 5 stars
3,"Xiaomi Mi Redmi 8 Smartphone (Onyx Black, 4GB ...","₹11,999.00",4.0 out of 5 stars
4,Ambrane 20000mAh Power Bank with 22.5W Fast Ch...,"₹1,299.00",3.7 out of 5 stars
...,...,...,...
131,"Smart Watch for Men, Bluetooth (Answer/Make Ca...","₹10,978.00",4.3 out of 5 stars
132,Samsung Official S22 Smart Clear View Cover Wh...,"₹13,156.00",4.6 out of 5 stars
133,Smartphone Accessory Front Housing LCD Frame B...,"₹9,579.00",NaN
134,Smartphone Accessory Front Housing LCD Frame B...,"₹9,579.00",NaN
135,Yedidya for Samsung Galaxy S25 Case 5G Smart V...,"₹2,389.00",NaN

In [ ]:
# Checking the data types
df.dtypes

Device        str
Price     float64
Rating        str
dtype: object

In [ ]:
# Checking the data types
df2.dtypes

Device    str
Price     str
Rating    str
dtype: object

In [ ]:
# Changing the data type of 'Price' Column
df['Price'] = df['Price'].str.replace('₹', '', regex=False).str.replace(',', "", regex=False).astype('float')

In [ ]:
# Changing the data type of 'Price' Column
df2['Price'] = df2['Price'].str.replace("₹", '',regex=False).str.replace(",", "", regex=False).astype(float)

In [ ]:
# Changing the data type of 'Rating' Column
df['Rating'] = df['Rating'].str.split().str[0].astype(float)

In [ ]:
# Changing the data type of 'Rating' Column
df2['Rating'] = df2['Rating'].str.split().str[0].astype(float)

In [ ]:
# Checking for Devices having Price more than 35k
df[df['Price'] > 35000].sort_values('Price', ascending=False)

Empty DataFrame
Columns: [Device, Price, Rating, price]
Index: []

In [ ]:
# Checking for Devices having Price more than 35k
df2[df2['Price'] > 35000].sort_values('Price', ascending=False)

Empty DataFrame
Columns: [Device, Price, Rating, price]
Index: []

In [ ]:
# Exporting the cleansed Dataset to .csv
df.to_csv('Data/Cleansed_df.csv', index=False)

In [ ]:
# Exporting the cleansed Dataset to .csv
df2.to_csv('Data/Cleansed_df2.csv', index=False)

In [ ]:
df1 = pd.read_csv('Data/Cleansed_df.csv')
df2 = pd.read_csv('Data/Cleansed_df2.csv')

In [ ]:
combined_df = pd.concat([df1, df2], ignore_index=True)

In [ ]:
combined_df.to_csv('Data/final_data.csv', index=False)